In [20]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [21]:
df = pd.read_csv(
    "../data/processed_hospital_data.csv"
)

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (12000, 20)

,Queue_Length,Doctors_Available,Appointments_Count,Consultation_Duration_Min,Appointment_Month,Appointment_Day,Day_of_Week,Is_Weekend,Appointment_Hour,Peak_Hour,Arrival_Delay_Minutes,Department_Dermatology,Department_ENT,Department_General Medicine,Department_Gynecology,Department_Neurology,Department_Orthopedics,Department_Pediatrics,Patient_Type_Returning,Waiting_Time_Minutes
0,11,3,20,21,1,1,3,0,8,0,-6,False,True,False,False,False,False,False,False,20
1,8,1,31,12,1,1,3,0,9,0,23,False,False,True,False,False,False,False,True,28
2,7,1,27,25,1,1,3,0,9,0,16,False,False,False,False,False,True,False,False,34
3,10,2,25,16,1,1,3,0,10,1,-6,False,False,True,False,False,False,False,False,23
4,12,3,29,22,1,1,3,0,10,1,-3,False,False,False,True,False,False,False,True,15

In [22]:
X = df.drop(
    columns=["Waiting_Time_Minutes"]
)

y = df["Waiting_Time_Minutes"]

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (12000, 19)
y Shape: (12000,)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 9600
Testing samples: 2400

In [24]:
linear_model = LinearRegression()

linear_model.fit(
    X_train,
    y_train
)

print("Linear Regression model trained successfully!")

Linear Regression model trained successfully!

In [25]:
y_pred_linear = linear_model.predict(
    X_test
)

print("First 10 predictions:")
print(y_pred_linear[:10])

First 10 predictions:
[14.88096523 12.64479627 20.76459674 16.54525514 20.11715723 21.49205223
 10.54373434 23.31916257 11.91477027 26.00354498]

In [26]:
mae = mean_absolute_error(
    y_test,
    y_pred_linear
)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_linear
    )
)

r2 = r2_score(
    y_test,
    y_pred_linear
)

print("Linear Regression Results")
print("-------------------------")
print("MAE :", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R²  :", round(r2, 2))

Linear Regression Results
-------------------------
MAE : 3.89
RMSE: 4.84
R²  : 0.78

In [27]:
from sklearn.tree import DecisionTreeRegressor

In [28]:
tree_model = DecisionTreeRegressor(
    max_depth=8,
    random_state=42
)

In [29]:
tree_model.fit(
    X_train,
    y_train
)

print("Decision Tree model trained successfully!")

Decision Tree model trained successfully!

In [30]:
y_pred_tree = tree_model.predict(
    X_test
)

print("First 10 predictions:")
print(y_pred_tree[:10])

First 10 predictions:
[14.75789474 12.3125     20.44303797 17.94736842 17.25641026 23.11650485
  8.8559322  25.75        9.38461538 18.85294118]

In [31]:
tree_mae = mean_absolute_error(
    y_test,
    y_pred_tree
)

tree_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_tree
    )
)

tree_r2 = r2_score(
    y_test,
    y_pred_tree
)

print("Decision Tree Results")
print("---------------------")
print("MAE :", round(tree_mae, 2))
print("RMSE:", round(tree_rmse, 2))
print("R²  :", round(tree_r2, 2))

Decision Tree Results
---------------------
MAE : 3.94
RMSE: 5.06
R²  : 0.76

In [32]:
y_pred_tree = tree_model.predict(X_test)

print("First 10 predictions:")
print(y_pred_tree[:10])

First 10 predictions:
[14.75789474 12.3125     20.44303797 17.94736842 17.25641026 23.11650485
  8.8559322  25.75        9.38461538 18.85294118]

In [33]:
tree_mae = mean_absolute_error(
    y_test,
    y_pred_tree
)

tree_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_tree
    )
)

tree_r2 = r2_score(
    y_test,
    y_pred_tree
)

print("Decision Tree Results")
print("---------------------")
print("MAE :", round(tree_mae, 2))
print("RMSE:", round(tree_rmse, 2))
print("R²  :", round(tree_r2, 2))

Decision Tree Results
---------------------
MAE : 3.94
RMSE: 5.06
R²  : 0.76

In [34]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!

In [35]:
y_pred_rf = rf_model.predict(X_test)

print("First 10 Random Forest predictions:")
print(y_pred_rf[:10])

First 10 Random Forest predictions:
[15.01140324 11.06000224 19.67111943 14.95901475 16.06061692 22.28614798
  7.70971379 27.70760048 10.49563531 22.14179249]

In [36]:
rf_mae = mean_absolute_error(
    y_test,
    y_pred_rf
)

rf_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_rf
    )
)

rf_r2 = r2_score(
    y_test,
    y_pred_rf
)

print("Random Forest Results")
print("---------------------")
print("MAE :", round(rf_mae, 2))
print("RMSE:", round(rf_rmse, 2))
print("R²  :", round(rf_r2, 2))

Random Forest Results
---------------------
MAE : 3.76
RMSE: 4.77
R²  : 0.79

In [37]:
from sklearn.ensemble import GradientBoostingRegressor

gb_model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

gb_model.fit(X_train, y_train)

print("Gradient Boosting model trained successfully!")

Gradient Boosting model trained successfully!

In [38]:
y_pred_gb = gb_model.predict(X_test)

print("First 10 Gradient Boosting predictions:")
print(y_pred_gb[:10])

First 10 Gradient Boosting predictions:
[13.89518494 11.89702858 19.85108901 15.36265266 19.00811656 21.86651701
  8.97539755 24.01855854 10.54353005 22.89036025]

In [39]:
gb_mae = mean_absolute_error(
    y_test,
    y_pred_gb
)

gb_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_gb
    )
)

gb_r2 = r2_score(
    y_test,
    y_pred_gb
)

print("Gradient Boosting Results")
print("--------------------------")
print("MAE :", round(gb_mae, 2))
print("RMSE:", round(gb_rmse, 2))
print("R²  :", round(gb_r2, 2))

Gradient Boosting Results
--------------------------
MAE : 3.69
RMSE: 4.7
R²  : 0.79

In [40]:
model_comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "MAE": [
        3.89,
        3.94,
        3.76,
        3.69
    ],
    "RMSE": [
        4.84,
        5.06,
        4.77,
        4.70
    ],
    "R2": [
        0.78,
        0.76,
        0.79,
        0.79
    ]
})

model_comparison

               Model   MAE  RMSE    R2
0  Linear Regression  3.89  4.84  0.78
1      Decision Tree  3.94  5.06  0.76
2      Random Forest  3.76  4.77  0.79
3  Gradient Boosting  3.69  4.70  0.79

In [41]:
import joblib

joblib.dump(
    gb_model,
    "../models/waiting_time_model.pkl"
)

print("Waiting time model saved successfully!")

Waiting time model saved successfully!

In [42]:
import joblib

loaded_model = joblib.load("../models/waiting_time_model.pkl")

print("Waiting time model loaded successfully!")
print("Model type:", type(loaded_model).__name__)

Waiting time model loaded successfully!
Model type: GradientBoostingRegressor

In [43]:
import pandas as pd

df_crowd = pd.read_csv("../data/hospital_data.csv")

print("Dataset loaded successfully!")
print("Shape:", df_crowd.shape)
print(df_crowd.head())

Dataset loaded successfully!
Shape: (12000, 12)
  Patient_ID Appointment_Date Appointment_Time Arrival_Time        Department  \
0     P05732       2026-01-01            08:00        07:54               ENT
1     P02024       2026-01-01            09:10        09:33  General Medicine
2     P00180       2026-01-01            09:30        09:46       Orthopedics
3     P03650       2026-01-01            10:00        09:54  General Medicine
4     P03679       2026-01-01            10:20        10:17        Gynecology

  Doctor_ID Patient_Type  Queue_Length  Doctors_Available  Appointments_Count  \
0    DOC013          New            11                  3                  20
1    DOC016    Returning             8                  1                  31
2    DOC016          New             7                  1                  27
3    DOC003          New            10                  2                  25
4    DOC013    Returning            12                  3                  29

   Consultation_Duration_Min  Waiting_Time_Minutes
0                         21                    20
1                         12                    28
2                         25                    34
3                         16                    23
4                         22                    15

In [44]:
def classify_crowd(queue):
    if queue <= 8:
        return "Low"
    elif queue <= 15:
        return "Moderate"
    else:
        return "High"


df_crowd["Crowd_Level"] = df_crowd["Queue_Length"].apply(classify_crowd)

print("Crowd level created successfully!")

print("\nCrowd Level Distribution:")
print(df_crowd["Crowd_Level"].value_counts())

print("\nFirst 10 records:")
print(df_crowd[["Queue_Length", "Crowd_Level"]].head(10))

Crowd level created successfully!

Crowd Level Distribution:
Crowd_Level
Moderate    8311
Low         1866
High        1823
Name: count, dtype: int64

First 10 records:
   Queue_Length Crowd_Level
0            11    Moderate
1             8         Low
2             7         Low
3            10    Moderate
4            12    Moderate
5            14    Moderate
6             9    Moderate
7            11    Moderate
8            11    Moderate
9            11    Moderate

In [45]:
print("Crowd Level Counts:")
print(df_crowd["Crowd_Level"].value_counts())

print("\nCrowd Level Percentages:")
print(
    (df_crowd["Crowd_Level"].value_counts(normalize=True) * 100)
    .round(2)
)

Crowd Level Counts:
Crowd_Level
Moderate    8311
Low         1866
High        1823
Name: count, dtype: int64

Crowd Level Percentages:
Crowd_Level
Moderate    69.26
Low         15.55
High        15.19
Name: proportion, dtype: float64

In [46]:
from sklearn.model_selection import train_test_split

X_crowd = df_crowd[
    [
        "Queue_Length",
        "Doctors_Available",
        "Appointments_Count",
        "Consultation_Duration_Min"
    ]
]

y_crowd = df_crowd["Crowd_Level"]

print("X Shape:", X_crowd.shape)
print("y Shape:", y_crowd.shape)

X Shape: (12000, 4)
y Shape: (12000,)

In [47]:
X_train_crowd, X_test_crowd, y_train_crowd, y_test_crowd = train_test_split(
    X_crowd,
    y_crowd,
    test_size=0.20,
    random_state=42,
    stratify=y_crowd
)

print("Training samples:", len(X_train_crowd))
print("Testing samples:", len(X_test_crowd))

print("\nTraining class distribution:")
print(y_train_crowd.value_counts())

print("\nTesting class distribution:")
print(y_test_crowd.value_counts())

Training samples: 9600
Testing samples: 2400

Training class distribution:
Crowd_Level
Moderate    6649
Low         1493
High        1458
Name: count, dtype: int64

Testing class distribution:
Crowd_Level
Moderate    1662
Low          373
High         365
Name: count, dtype: int64

In [48]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(
    X_train_crowd,
    y_train_crowd
)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [49]:
y_pred_logistic = logistic_model.predict(X_test_crowd)

print("First 20 Logistic Regression predictions:")
print(y_pred_logistic[:20])

First 20 Logistic Regression predictions:
['Moderate' 'Moderate' 'Moderate' 'Moderate' 'Low' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Low' 'Low' 'Moderate' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Moderate' 'Moderate']

In [50]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

logistic_accuracy = accuracy_score(
    y_test_crowd,
    y_pred_logistic
)

logistic_precision = precision_score(
    y_test_crowd,
    y_pred_logistic,
    average="weighted"
)

logistic_recall = recall_score(
    y_test_crowd,
    y_pred_logistic,
    average="weighted"
)

logistic_f1 = f1_score(
    y_test_crowd,
    y_pred_logistic,
    average="weighted"
)

print("Logistic Regression Results")
print("---------------------------")
print("Accuracy :", round(logistic_accuracy, 2))
print("Precision:", round(logistic_precision, 2))
print("Recall   :", round(logistic_recall, 2))
print("F1-Score :", round(logistic_f1, 2))

print("\nClassification Report:")
print(classification_report(y_test_crowd, y_pred_logistic))

print("Confusion Matrix:")
print(confusion_matrix(y_test_crowd, y_pred_logistic))

Logistic Regression Results
---------------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-Score : 1.0

Classification Report:
              precision    recall  f1-score   support

        High       1.00      1.00      1.00       365
         Low       1.00      1.00      1.00       373
    Moderate       1.00      1.00      1.00      1662

    accuracy                           1.00      2400
   macro avg       1.00      1.00      1.00      2400
weighted avg       1.00      1.00      1.00      2400

Confusion Matrix:
[[ 365    0    0]
 [   0  373    0]
 [   0    0 1662]]

In [51]:
from sklearn.tree import DecisionTreeClassifier

tree_classifier = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

tree_classifier.fit(
    X_train_crowd,
    y_train_crowd
)

print("Decision Tree Classifier trained successfully!")

Decision Tree Classifier trained successfully!

In [52]:
y_pred_tree_crowd = tree_classifier.predict(X_test_crowd)

print("First 20 Decision Tree predictions:")
print(y_pred_tree_crowd[:20])

First 20 Decision Tree predictions:
['Moderate' 'Moderate' 'Moderate' 'Moderate' 'Low' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Low' 'Low' 'Moderate' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Moderate' 'Moderate']

In [53]:
tree_accuracy = accuracy_score(
    y_test_crowd,
    y_pred_tree_crowd
)

tree_precision = precision_score(
    y_test_crowd,
    y_pred_tree_crowd,
    average="weighted"
)

tree_recall = recall_score(
    y_test_crowd,
    y_pred_tree_crowd,
    average="weighted"
)

tree_f1 = f1_score(
    y_test_crowd,
    y_pred_tree_crowd,
    average="weighted"
)

print("Decision Tree Classifier Results")
print("--------------------------------")
print("Accuracy :", round(tree_accuracy, 2))
print("Precision:", round(tree_precision, 2))
print("Recall   :", round(tree_recall, 2))
print("F1-Score :", round(tree_f1, 2))

print("\nClassification Report:")
print(classification_report(
    y_test_crowd,
    y_pred_tree_crowd
))

print("Confusion Matrix:")
print(confusion_matrix(
    y_test_crowd,
    y_pred_tree_crowd
))

Decision Tree Classifier Results
--------------------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-Score : 1.0

Classification Report:
              precision    recall  f1-score   support

        High       1.00      1.00      1.00       365
         Low       1.00      1.00      1.00       373
    Moderate       1.00      1.00      1.00      1662

    accuracy                           1.00      2400
   macro avg       1.00      1.00      1.00      2400
weighted avg       1.00      1.00      1.00      2400

Confusion Matrix:
[[ 365    0    0]
 [   0  373    0]
 [   0    0 1662]]

In [54]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    random_state=42,
    n_jobs=-1
)

rf_classifier.fit(
    X_train_crowd,
    y_train_crowd
)

print("Random Forest Classifier trained successfully!")

Random Forest Classifier trained successfully!

In [55]:
y_pred_rf_crowd = rf_classifier.predict(X_test_crowd)

print("First 20 Random Forest predictions:")
print(y_pred_rf_crowd[:20])

First 20 Random Forest predictions:
['Moderate' 'Moderate' 'Moderate' 'Moderate' 'Low' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Low' 'Low' 'Moderate' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Moderate' 'Moderate']

In [56]:
rf_accuracy = accuracy_score(
    y_test_crowd,
    y_pred_rf_crowd
)

rf_precision = precision_score(
    y_test_crowd,
    y_pred_rf_crowd,
    average="weighted"
)

rf_recall = recall_score(
    y_test_crowd,
    y_pred_rf_crowd,
    average="weighted"
)

rf_f1 = f1_score(
    y_test_crowd,
    y_pred_rf_crowd,
    average="weighted"
)

print("Random Forest Classifier Results")
print("---------------------------------")
print("Accuracy :", round(rf_accuracy, 2))
print("Precision:", round(rf_precision, 2))
print("Recall   :", round(rf_recall, 2))
print("F1-Score :", round(rf_f1, 2))

print("\nClassification Report:")
print(classification_report(
    y_test_crowd,
    y_pred_rf_crowd
))

print("Confusion Matrix:")
print(confusion_matrix(
    y_test_crowd,
    y_pred_rf_crowd
))

Random Forest Classifier Results
---------------------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-Score : 1.0

Classification Report:
              precision    recall  f1-score   support

        High       1.00      1.00      1.00       365
         Low       1.00      1.00      1.00       373
    Moderate       1.00      1.00      1.00      1662

    accuracy                           1.00      2400
   macro avg       1.00      1.00      1.00      2400
weighted avg       1.00      1.00      1.00      2400

Confusion Matrix:
[[ 365    0    0]
 [   0  373    0]
 [   0    0 1662]]

In [57]:
from sklearn.ensemble import GradientBoostingClassifier

gb_classifier = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_classifier.fit(
    X_train_crowd,
    y_train_crowd
)

print("Gradient Boosting Classifier trained successfully!")

Gradient Boosting Classifier trained successfully!

In [58]:
y_pred_gb_crowd = gb_classifier.predict(X_test_crowd)

print("First 20 Gradient Boosting predictions:")
print(y_pred_gb_crowd[:20])

First 20 Gradient Boosting predictions:
['Moderate' 'Moderate' 'Moderate' 'Moderate' 'Low' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Low' 'Low' 'Moderate' 'High' 'Moderate'
 'Moderate' 'Moderate' 'Moderate' 'Moderate' 'Moderate']

In [59]:
gb_accuracy = accuracy_score(
    y_test_crowd,
    y_pred_gb_crowd
)

gb_precision = precision_score(
    y_test_crowd,
    y_pred_gb_crowd,
    average="weighted"
)

gb_recall = recall_score(
    y_test_crowd,
    y_pred_gb_crowd,
    average="weighted"
)

gb_f1 = f1_score(
    y_test_crowd,
    y_pred_gb_crowd,
    average="weighted"
)

print("Gradient Boosting Classifier Results")
print("------------------------------------")
print("Accuracy :", round(gb_accuracy, 2))
print("Precision:", round(gb_precision, 2))
print("Recall   :", round(gb_recall, 2))
print("F1-Score :", round(gb_f1, 2))

print("\nClassification Report:")
print(classification_report(
    y_test_crowd,
    y_pred_gb_crowd
))

print("Confusion Matrix:")
print(confusion_matrix(
    y_test_crowd,
    y_pred_gb_crowd
))

Gradient Boosting Classifier Results
------------------------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-Score : 1.0

Classification Report:
              precision    recall  f1-score   support

        High       1.00      1.00      1.00       365
         Low       1.00      1.00      1.00       373
    Moderate       1.00      1.00      1.00      1662

    accuracy                           1.00      2400
   macro avg       1.00      1.00      1.00      2400
weighted avg       1.00      1.00      1.00      2400

Confusion Matrix:
[[ 365    0    0]
 [   0  373    0]
 [   0    0 1662]]

In [60]:
crowd_model_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        logistic_accuracy,
        tree_accuracy,
        rf_accuracy,
        gb_accuracy
    ],
    "Precision": [
        logistic_precision,
        tree_precision,
        rf_precision,
        gb_precision
    ],
    "Recall": [
        logistic_recall,
        tree_recall,
        rf_recall,
        gb_recall
    ],
    "F1-Score": [
        logistic_f1,
        tree_f1,
        rf_f1,
        gb_f1
    ]
})

crowd_model_comparison

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression       1.0        1.0     1.0       1.0
1        Decision Tree       1.0        1.0     1.0       1.0
2        Random Forest       1.0        1.0     1.0       1.0
3    Gradient Boosting       1.0        1.0     1.0       1.0

In [61]:
import joblib

joblib.dump(
    rf_classifier,
    "../models/crowd_model.pkl"
)

print("Crowd level model saved successfully!")

Crowd level model saved successfully!

In [62]:
import joblib

# Load waiting time model
loaded_waiting_model = joblib.load(
    "../models/waiting_time_model.pkl"
)

# Load crowd level model
loaded_crowd_model = joblib.load(
    "../models/crowd_model.pkl"
)

print("Both models loaded successfully!")

print("\nWaiting Time Model:")
print(type(loaded_waiting_model).__name__)

print("\nCrowd Level Model:")
print(type(loaded_crowd_model).__name__)

Both models loaded successfully!

Waiting Time Model:
GradientBoostingRegressor

Crowd Level Model:
RandomForestClassifier